In [7]:
import pandas as pd
import cufflinks as cf
cf.go_offline(connected=True)
# Укажите путь к файлу "household_power_consumption.txt"
data = pd.read_csv('Sunspots.csv', low_memory=False, infer_datetime_format=True, index_col=['Date'], dayfirst=True)
data = data.rename(columns={'Monthly Mean Total Sunspot Number':'Sunspots'})
data = data.drop('Unnamed: 0', axis=1)
# Визуализация данных (например, потребление энергии по глобальной активной мощности)
data['Sunspots'].iplot(title='Sunspots', xTitle='Date', yTitle='Sunspots')


/tmp/ipykernel_707045/946476137.py:5: FutureWarning:

The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.



In [10]:
#df['Global_active_power'] = df[['Global_active_power']]
data

Sunspots  Lag_1  Lag_2  Lag_3  Lag_4  Lag_5  Lag_6  Lag_7  Lag_8  \
Date                                                                           
1749-01-31      96.7    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
1749-02-28     104.3   96.7    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
1749-03-31     116.7  104.3   96.7    NaN    NaN    NaN    NaN    NaN    NaN   
1749-04-30      92.8  116.7  104.3   96.7    NaN    NaN    NaN    NaN    NaN   
1749-05-31     141.7   92.8  116.7  104.3   96.7    NaN    NaN    NaN    NaN   
...              ...    ...    ...    ...    ...    ...    ...    ...    ...   
2020-09-30       0.6    7.5    6.1    5.8    0.2    5.2    1.5    0.2    6.2   
2020-10-31      14.4    0.6    7.5    6.1    5.8    0.2    5.2    1.5    0.2   
2020-11-30      34.0   14.4    0.6    7.5    6.1    5.8    0.2    5.2    1.5   
2020-12-31      21.8   34.0   14.4    0.6    7.5    6.1    5.8    0.2    5.2   
2021-01-31      10.4   21.8   34.0   14.4    0.6    7.5    6.1    5.8    0.2   

            Lag_9  ...  Autocorr_1  Autocorr_2  Autocorr_3  Autocorr_4  \
Date               ...                                                   
1749-01-31    NaN  ...    0.918247    0.886031    0.870086    0.859613   
1749-02-28    NaN  ...    0.918247    0.886031    0.870086    0.859613   
1749-03-31    NaN  ...    0.918247    0.886031    0.870086    0.859613   
1749-04-30    NaN  ...    0.918247    0.886031    0.870086    0.859613   
1749-05-31    NaN  ...    0.918247    0.886031    0.870086    0.859613   
...           ...  ...         ...         ...         ...         ...   
2020-09-30    1.5  ...    0.918247    0.886031    0.870086    0.859613   
2020-10-31    6.2  ...    0.918247    0.886031    0.870086    0.859613   
2020-11-30    0.2  ...    0.918247    0.886031    0.870086    0.859613   
2020-12-31    1.5  ...    0.918247    0.886031    0.870086    0.859613   
2021-01-31    5.2  ...    0.918247    0.886031    0.870086    0.859613   

            Autocorr_5  Autocorr_6  Autocorr_7  Autocorr_8  Autocorr_9  \
Date                                                                     
1749-01-31    0.845171    0.832597    0.814262    0.800902    0.791447   
1749-02-28    0.845171    0.832597    0.814262    0.800902    0.791447   
1749-03-31    0.845171    0.832597    0.814262    0.800902    0.791447   
1749-04-30    0.845171    0.832597    0.814262    0.800902    0.791447   
1749-05-31    0.845171    0.832597    0.814262    0.800902    0.791447   
...                ...         ...         ...         ...         ...   
2020-09-30    0.845171    0.832597    0.814262    0.800902    0.791447   
2020-10-31    0.845171    0.832597    0.814262    0.800902    0.791447   
2020-11-30    0.845171    0.832597    0.814262    0.800902    0.791447   
2020-12-31    0.845171    0.832597    0.814262    0.800902    0.791447   
2021-01-31    0.845171    0.832597    0.814262    0.800902    0.791447   

            Autocorr_10  
Date                     
1749-01-31     0.771596  
1749-02-28     0.771596  
1749-03-31     0.771596  
1749-04-30     0.771596  
1749-05-31     0.771596  
...                 ...  
2020-09-30     0.771596  
2020-10-31     0.771596  
2020-11-30     0.771596  
2020-12-31     0.771596  
2021-01-31     0.771596  

[3265 rows x 31 columns]

In [9]:
import pandas as pd
import numpy as np

def prepare_data(df, lags=10, diff=10, count_autocor=10):
    # Извлечение 10 лагов
    for i in range(1, lags+1):
        df[f'Lag_{i}'] = df['Sunspots'].shift(i)

    # Извлечение 10 разностей
    for i in range(1, diff+1):
        df[f'Diff_{i}'] = df['Sunspots'].diff(i)

    # Извлечение 10 автокорреляций
    for i in range(1, count_autocor+1):
        df[f'Autocorr_{i}'] = df['Sunspots'].autocorr(lag=i)

    # Удаление строк с NaN значениями
    return df
data_n = prepare_data(data)

In [ ]:
# Извлечение 10 автокорреляций
# temp_dict={}
# for i in range(len(df['Global_active_power'])):
#     for j in range(1, 11):
#         if j == 1:
#             temp_dict[i] = [df['Global_active_power'].iloc[:i].autocorr(lag=j)]
#         else:
#             temp_dict[i].extend([df['Global_active_power'].iloc[:i].autocorr(lag=j)])

In [ ]:
# temp_dict

In [21]:
data_n.iloc[:,np.arange(0,10)].iplot()

In [23]:
data_n.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3265 entries, 1749-01-31 to 2021-01-31
Data columns (total 31 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Sunspots     3265 non-null   float64
 1   Lag_1        3264 non-null   float64
 2   Lag_2        3263 non-null   float64
 3   Lag_3        3262 non-null   float64
 4   Lag_4        3261 non-null   float64
 5   Lag_5        3260 non-null   float64
 6   Lag_6        3259 non-null   float64
 7   Lag_7        3258 non-null   float64
 8   Lag_8        3257 non-null   float64
 9   Lag_9        3256 non-null   float64
 10  Lag_10       3255 non-null   float64
 11  Diff_1       3264 non-null   float64
 12  Diff_2       3263 non-null   float64
 13  Diff_3       3262 non-null   float64
 14  Diff_4       3261 non-null   float64
 15  Diff_5       3260 non-null   float64
 16  Diff_6       3259 non-null   float64
 17  Diff_7       3258 non-null   float64
 18  Diff_8       3257 non-null   float64
 

In [24]:
data_n.head()

Sunspots  Lag_1  Lag_2  Lag_3  Lag_4  Lag_5  Lag_6  Lag_7  Lag_8  \
Date                                                                           
1749-01-31      96.7    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
1749-02-28     104.3   96.7    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
1749-03-31     116.7  104.3   96.7    NaN    NaN    NaN    NaN    NaN    NaN   
1749-04-30      92.8  116.7  104.3   96.7    NaN    NaN    NaN    NaN    NaN   
1749-05-31     141.7   92.8  116.7  104.3   96.7    NaN    NaN    NaN    NaN   

            Lag_9  ...  Autocorr_1  Autocorr_2  Autocorr_3  Autocorr_4  \
Date               ...                                                   
1749-01-31    NaN  ...    0.918247    0.886031    0.870086    0.859613   
1749-02-28    NaN  ...    0.918247    0.886031    0.870086    0.859613   
1749-03-31    NaN  ...    0.918247    0.886031    0.870086    0.859613   
1749-04-30    NaN  ...    0.918247    0.886031    0.870086    0.859613   
1749-05-31    NaN  ...    0.918247    0.886031    0.870086    0.859613   

            Autocorr_5  Autocorr_6  Autocorr_7  Autocorr_8  Autocorr_9  \
Date                                                                     
1749-01-31    0.845171    0.832597    0.814262    0.800902    0.791447   
1749-02-28    0.845171    0.832597    0.814262    0.800902    0.791447   
1749-03-31    0.845171    0.832597    0.814262    0.800902    0.791447   
1749-04-30    0.845171    0.832597    0.814262    0.800902    0.791447   
1749-05-31    0.845171    0.832597    0.814262    0.800902    0.791447   

            Autocorr_10  
Date                     
1749-01-31     0.771596  
1749-02-28     0.771596  
1749-03-31     0.771596  
1749-04-30     0.771596  
1749-05-31     0.771596  

[5 rows x 31 columns]

In [26]:
data_n["Target"] = data_n["Sunspots"].shift(-1)


In [27]:
data_n.head()

Sunspots  Lag_1  Lag_2  Lag_3  Lag_4  Lag_5  Lag_6  Lag_7  Lag_8  \
Date                                                                           
1749-01-31      96.7    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
1749-02-28     104.3   96.7    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
1749-03-31     116.7  104.3   96.7    NaN    NaN    NaN    NaN    NaN    NaN   
1749-04-30      92.8  116.7  104.3   96.7    NaN    NaN    NaN    NaN    NaN   
1749-05-31     141.7   92.8  116.7  104.3   96.7    NaN    NaN    NaN    NaN   

            Lag_9  ...  Autocorr_2  Autocorr_3  Autocorr_4  Autocorr_5  \
Date               ...                                                   
1749-01-31    NaN  ...    0.886031    0.870086    0.859613    0.845171   
1749-02-28    NaN  ...    0.886031    0.870086    0.859613    0.845171   
1749-03-31    NaN  ...    0.886031    0.870086    0.859613    0.845171   
1749-04-30    NaN  ...    0.886031    0.870086    0.859613    0.845171   
1749-05-31    NaN  ...    0.886031    0.870086    0.859613    0.845171   

            Autocorr_6  Autocorr_7  Autocorr_8  Autocorr_9  Autocorr_10  \
Date                                                                      
1749-01-31    0.832597    0.814262    0.800902    0.791447     0.771596   
1749-02-28    0.832597    0.814262    0.800902    0.791447     0.771596   
1749-03-31    0.832597    0.814262    0.800902    0.791447     0.771596   
1749-04-30    0.832597    0.814262    0.800902    0.791447     0.771596   
1749-05-31    0.832597    0.814262    0.800902    0.791447     0.771596   

            Target  
Date                
1749-01-31   104.3  
1749-02-28   116.7  
1749-03-31    92.8  
1749-04-30   141.7  
1749-05-31   139.2  

[5 rows x 32 columns]

In [28]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, MaxAbsScaler, RobustScaler

# Пример данных
data_demo = np.array([[1.0, 2.0, 3.0],
                 [4.0, 5.0, 6.0],
                 [7.0, 8.0, 9.0]])

# 1. StandardScaler (стандартное отклонение)
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data_demo)
print("StandardScaler:")
print(scaled_data)

# 2. MinMaxScaler (минимум-максимум масштабирование)
minmax_scaler = MinMaxScaler()
minmax_scaled_data = minmax_scaler.fit_transform(data_demo)
print("\nMinMaxScaler:")
print(minmax_scaled_data)

# 3. MaxAbsScaler (масштабирование по максимальному абсолютному значению)
maxabs_scaler = MaxAbsScaler()
maxabs_scaled_data = maxabs_scaler.fit_transform(data_demo)
print("\nMaxAbsScaler:")
print(maxabs_scaled_data)

# 4. RobustScaler (робастное масштабирование)
robust_scaler = RobustScaler()
robust_scaled_data = robust_scaler.fit_transform(data_demo)
print("\nRobustScaler:")
print(robust_scaled_data)


StandardScaler:
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]

MinMaxScaler:
[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]

MaxAbsScaler:
[[0.14285714 0.25       0.33333333]
 [0.57142857 0.625      0.66666667]
 [1.         1.         1.        ]]

RobustScaler:
[[-1. -1. -1.]
 [ 0.  0.  0.]
 [ 1.  1.  1.]]


In [50]:
from sklearn.model_selection import TimeSeriesSplit

data_n = data_n.dropna()

# Разбиение данных на тренировочный и тестовый наборы
split_ratio = 0.8  # Процент данных для тренировки
split_index = int(split_ratio * len(data_n))

train_data = data_n.iloc[:split_index]
test_data = data_n.iloc[split_index:]

# Инициализация и применение RobustScaler к всем признакам, кроме целевой переменной
#scaler = RobustScaler()
scaler = StandardScaler()
train_data.iloc[:, 1:-1] = scaler.fit_transform(train_data.iloc[:, 1:-1])
test_data.iloc[:, 1:-1] = scaler.transform(test_data.iloc[:, 1:-1])

# Разделение на признаки и целевую переменную
X_train = train_data.iloc[:, 1:-1]
y_train = train_data['Target']
X_test = test_data.iloc[:, 1:-1]
y_test = test_data['Target']




In [51]:
# Проверка результатов
print("X_train (нормализованные признаки для тренировки):\n", X_train)
print("\nX_test (нормализованные признаки для теста):\n", X_test)
print("\ny_train (целевая переменная для тренировки):\n", y_train)
print("\ny_test (целевая переменная для теста):\n", y_test)

X_train (нормализованные признаки для тренировки):
                Lag_1     Lag_2     Lag_3     Lag_4     Lag_5     Lag_6  \
Date                                                                     
1749-11-30  0.672373  0.682372  0.445288  1.147746  0.868931  0.905379   
1749-12-31  2.723171  0.672008  0.682173  0.444664  1.147166  0.868385   
1750-01-31  0.912249  2.722628  0.671810  0.681492  0.444178  1.146578   
1750-02-28  0.619067  0.911863  2.722352  0.671131  0.680974  0.443698   
1750-03-31  0.682738  0.618706  0.911656  2.721168  0.670614  0.680457   
...              ...       ...       ...       ...       ...       ...   
1966-05-31 -0.168677 -0.651642 -0.668076 -0.594416 -0.825638 -0.854041   
1966-06-30 -0.239752 -0.168969 -0.651790 -0.668424 -0.594763 -0.825926   
1966-07-31 -0.187926 -0.240037 -0.169135 -0.652143 -0.668761 -0.595086   
1966-08-31 -0.002836 -0.188217 -0.240201 -0.169607 -0.652482 -0.669073   
1966-09-30 -0.115371 -0.003143 -0.188382 -0.240655 -0.170010

In [52]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Bidirectional, LSTM, Dense
from tensorflow.keras.callbacks import EarlyStopping


# Создание модели Bidirectional RNN
model = Sequential()
model.add(Bidirectional(LSTM(64, return_sequences=False), input_shape=(X_train.shape[1], 1)))
model.add(Dense(1))

# Компиляция модели
model.compile(optimizer='adam', loss='mean_squared_error')

# Обучение модели
early_stopping = EarlyStopping(patience=5, restore_best_weights=True)  # Остановка обучения при отсутствии улучшений
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))  # Изменение формы данных для LSTM
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
model.fit(X_train, y_train, epochs=50, batch_size=32, validation_data=(X_test, y_test), callbacks=[early_stopping])

# Оценка модели на тестовых данных
loss = model.evaluate(X_test, y_test)
print(f"Loss on test data: {loss}")



Epoch 1/50
82/82 [==============================] - 11s 97ms/step - loss: 9449.5674 - val_loss: 9032.9854
Epoch 2/50
82/82 [==============================] - 8s 94ms/step - loss: 7328.1797 - val_loss: 7699.9395
Epoch 3/50
82/82 [==============================] - 7s 88ms/step - loss: 6368.5322 - val_loss: 6807.1904
Epoch 4/50
82/82 [==============================] - 8s 97ms/step - loss: 5725.9253 - val_loss: 6176.5747
Epoch 5/50
82/82 [==============================] - 8s 93ms/step - loss: 5286.7261 - val_loss: 5736.5664
Epoch 6/50
82/82 [==============================] - 8s 102ms/step - loss: 4995.7036 - val_loss: 5431.5005
Epoch 7/50
82/82 [==============================] - 6s 70ms/step - loss: 4807.4512 - val_loss: 5226.0859
Epoch 8/50
82/82 [==============================] - 6s 69ms/step - loss: 4688.9946 - val_loss: 5085.4019
Epoch 9/50
82/82 [==============================] - 5s 64ms/step - loss: 4607.4224 - val_loss: 4963.0908
Epoch 10/50
82/82 [==============================] - 

In [53]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error

# Получите прогнозы модели на тестовых данных (предположим, что модель называется model)
y_pred = model.predict(X_test).ravel()

# MAE (Mean Absolute Error)
mae = mean_absolute_error(y_test, y_pred)
print(f"Mean Absolute Error (MAE): {mae}")

# MAPE (Mean Absolute Percentage Error)
def calculate_mape(y_true, y_pred):
    y_pred=y_pred.ravel()
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

mape = calculate_mape(y_test, y_pred)
print(f"Mean Absolute Percentage Error (MAPE): {mape:.2f}%")
temp_df = pd.DataFrame(y_test.values,columns=['y_test'], index = y_test.index)
temp_df["y_pred"] = y_pred

21/21 [==============================] - 1s 20ms/step
Mean Absolute Error (MAE): 16.91295718004077
Mean Absolute Percentage Error (MAPE): inf%


In [54]:
temp_df.iplot()

In [55]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Bidirectional, GRU, Dense
from tensorflow.keras.callbacks import EarlyStopping


# Создание модели Bidirectional RNN
model = Sequential()
model.add(Bidirectional(GRU(64, return_sequences=False), input_shape=(X_train.shape[1], 1)))
model.add(Dense(1))

# Компиляция модели
model.compile(optimizer='adam', loss='mean_squared_error')

# Обучение модели
early_stopping = EarlyStopping(patience=5, restore_best_weights=True)  # Остановка обучения при отсутствии улучшений
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))  # Изменение формы данных для LSTM
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
model.fit(X_train, y_train, epochs=50, batch_size=32, validation_data=(X_test, y_test), callbacks=[early_stopping])

# Оценка модели на тестовых данных
loss = model.evaluate(X_test, y_test)
print(f"Loss on test data: {loss}")

Epoch 1/50
82/82 [==============================] - 9s 75ms/step - loss: 9285.7158 - val_loss: 8823.5420
Epoch 2/50
82/82 [==============================] - 5s 65ms/step - loss: 7162.9126 - val_loss: 7523.0015
Epoch 3/50
82/82 [==============================] - 6s 70ms/step - loss: 6236.4390 - val_loss: 6660.1299
Epoch 4/50
82/82 [==============================] - 5s 63ms/step - loss: 5619.4248 - val_loss: 6056.0322
Epoch 5/50
82/82 [==============================] - 7s 79ms/step - loss: 5205.6768 - val_loss: 5640.3926
Epoch 6/50
82/82 [==============================] - 6s 71ms/step - loss: 4937.0796 - val_loss: 5362.3335
Epoch 7/50
82/82 [==============================] - 6s 70ms/step - loss: 4766.1123 - val_loss: 5178.8853
Epoch 8/50
82/82 [==============================] - 7s 91ms/step - loss: 4654.8052 - val_loss: 5017.0522
Epoch 9/50
82/82 [==============================] - 5s 63ms/step - loss: 4103.5234 - val_loss: 3785.7915
Epoch 10/50
82/82 [==============================] - 7s

In [56]:
# Получите прогнозы модели на тестовых данных (предположим, что модель называется model)
y_pred = model.predict(X_test).ravel()

# MAE (Mean Absolute Error)
mae = mean_absolute_error(y_test, y_pred)
print(f"Mean Absolute Error (MAE): {mae}")

# MAPE (Mean Absolute Percentage Error)
def calculate_mape(y_true, y_pred):
    y_pred=y_pred.ravel()
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

mape = calculate_mape(y_test, y_pred)
print(f"Mean Absolute Percentage Error (MAPE): {mape:.2f}%")
temp_df = pd.DataFrame(y_test.values,columns=['y_test'], index = y_test.index)
temp_df["y_pred"] = y_pred

21/21 [==============================] - 1s 26ms/step
Mean Absolute Error (MAE): 16.982829618380734
Mean Absolute Percentage Error (MAPE): inf%


In [57]:
temp_df.iplot()

Для реализации механизма внимания Bahdanau для временных рядов, мы можем использовать библиотеку TensorFlow и Keras. В данном случае, мы рассмотрим использование механизма внимания Bahdanau в контексте прогнозирования временных рядов.

Вам потребуется предварительно обработать данные временного ряда и подготовить их в виде входной последовательности временных шагов и соответствующих целевых значений. Ниже приведен код для реализации механизма внимания Bahdanau для временных рядов:


In [66]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Input, LSTM, Dense, Attention
from tensorflow.keras.models import Model

# Гиперпараметры
sequence_length = 30  # Длина входной последовательности временных шагов
input_dim = 1  # Размерность признаков в каждом временном шаге
hidden_units = 256  # Размерность скрытого слоя LSTM
output_dim = 1  # Размерность выходного слоя
attention_units = 64  # Размерность внимания Bahdanau

# Создание входных данных
input_sequence = Input(shape=(sequence_length, input_dim))

# LSTM слой
lstm_layer = LSTM(hidden_units, return_sequences=False)(input_sequence)

# lstm_layer2 = LSTM(hidden_units, return_sequences=False)(lstm_layer)
# Механизм внимания Bahdanau
attention_layer = Attention(use_scale=True)([lstm_layer, lstm_layer])

# Конкатенация LSTM выхода и слоя внимания
merged_layer = tf.concat([lstm_layer, attention_layer], axis=-1)

# Полносвязанный слой для прогнозирования
output_layer = Dense(output_dim)(merged_layer)

# Создание модели
model = Model(inputs=input_sequence, outputs=output_layer)

# Компиляция модели
model.compile(optimizer='adam', loss='mean_squared_error')

# Вывод структуры модели
model.summary()


Model: "model_3"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_4 (InputLayer)           [(None, 30, 1)]      0           []                               
                                                                                                  
 lstm_9 (LSTM)                  (None, 256)          264192      ['input_4[0][0]']                
                                                                                                  
 attention_3 (Attention)        (None, 256)          1           ['lstm_9[0][0]',                 
                                                                  'lstm_9[0][0]']                 
                                                                                                  
 tf.concat_3 (TFOpLambda)       (None, 512)          0           ['lstm_9[0][0]',           

In [67]:
# Обучение модели
early_stopping = EarlyStopping(patience=5, restore_best_weights=True)  # Остановка обучения при отсутствии улучшений
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))  # Изменение формы данных для LSTM
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
model.fit(X_train, y_train, epochs=50, batch_size=128, validation_data=(X_test, y_test), callbacks=[early_stopping])

# Оценка модели на тестовых данных
loss = model.evaluate(X_test, y_test)
print(f"Loss on test data: {loss}")

Epoch 1/50


21/21 [==============================] - 8s 312ms/step - loss: 9653.1494 - val_loss: 9011.7148
Epoch 2/50
21/21 [==============================] - 7s 350ms/step - loss: 7570.8730 - val_loss: 7747.8701
Epoch 3/50
21/21 [==============================] - 9s 443ms/step - loss: 6328.8955 - val_loss: 6695.4521
Epoch 4/50
21/21 [==============================] - 7s 346ms/step - loss: 5635.5679 - val_loss: 6028.1807
Epoch 5/50
21/21 [==============================] - 8s 385ms/step - loss: 5176.8984 - val_loss: 5587.8374
Epoch 6/50
21/21 [==============================] - 8s 373ms/step - loss: 4898.3687 - val_loss: 5298.2388
Epoch 7/50
21/21 [==============================] - 9s 449ms/step - loss: 4730.2358 - val_loss: 5120.9014
Epoch 8/50
21/21 [==============================] - 10s 498ms/step - loss: 4636.6714 - val_loss: 5014.1890
Epoch 9/50
21/21 [==============================] - 9s 414ms/step - loss: 4590.4312 - val_loss: 4948.4307
Epoch 10/50
21/21 [==============================] - 7s 

In [68]:
# Получите прогнозы модели на тестовых данных (предположим, что модель называется model)
y_pred = model.predict(X_test)

# Преобразуйте прогнозы в одномерный массив
y_pred = y_pred.ravel()

# MAE (Mean Absolute Error)
mae = mean_absolute_error(y_test, y_pred)
print(f"Mean Absolute Error (MAE): {mae}")

# MAPE (Mean Absolute Percentage Error)
def calculate_mape(y_true, y_pred):
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

mape = calculate_mape(y_test, y_pred)
print(f"Mean Absolute Percentage Error (MAPE): {mape:.2f}%")

# Создайте DataFrame для сравнения и визуализации результатов
temp_df = pd.DataFrame({'y_test': y_test, 'y_pred': y_pred}, index=y_test.index)


21/21 [==============================] - 1s 37ms/step
Mean Absolute Error (MAE): 58.45069768527685
Mean Absolute Percentage Error (MAPE): inf%


In [69]:
temp_df.iplot()

In [72]:
import tensorflow as tf
from tensorflow.keras.layers import Input, LSTM, Dense, Attention
from tensorflow.keras.models import Model

# Гиперпараметры
sequence_length = 30  # Длина входной последовательности временных шагов
input_dim = 1  # Размерность признаков в каждом временном шаге
output_dim = 1  # Размерность выходного слоя
attention_units = 128  # Размерность внимания Luong

# Создание входных данных
input_sequence = Input(shape=(sequence_length, input_dim))

# LSTM слой
lstm_layer = LSTM(attention_units, return_sequences=True)(input_sequence)

# Механизм внимания Luong
attention_layer = Attention()([lstm_layer, lstm_layer])

# Взвешенная сумма выходов LSTM с использованием весов внимания
context_layer = tf.matmul(attention_layer, lstm_layer, transpose_a=True)

# Полносвязанный слой для прогнозирования
output_layer = Dense(output_dim)(context_layer)  # Нет необходимости объединять с LSTM

# Создание модели
model = Model(inputs=input_sequence, outputs=output_layer)

# Компиляция модели
model.compile(optimizer='adam', loss='mean_squared_error')

# Вывод структуры модели
model.summary()


Model: "model_5"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_6 (InputLayer)           [(None, 30, 1)]      0           []                               
                                                                                                  
 lstm_11 (LSTM)                 (None, 30, 128)      66560       ['input_6[0][0]']                
                                                                                                  
 attention_5 (Attention)        (None, 30, 128)      0           ['lstm_11[0][0]',                
                                                                  'lstm_11[0][0]']                
                                                                                                  
 tf.linalg.matmul_1 (TFOpLambda  (None, 128, 128)    0           ['attention_5[0][0]',      

In [73]:
# Обучение модели
early_stopping = EarlyStopping(patience=5, restore_best_weights=True)  # Остановка обучения при отсутствии улучшений
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))  # Изменение формы данных для LSTM
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
model.fit(X_train, y_train, epochs=50, batch_size=128, validation_data=(X_test, y_test), callbacks=[early_stopping])

# Оценка модели на тестовых данных
loss = model.evaluate(X_test, y_test)
print(f"Loss on test data: {loss}")

Epoch 1/50


2023-11-06 18:12:35.769552: W tensorflow/core/grappler/costs/op_level_cost_estimator.cc:690] Error in PredictCost() for the op: op: "Softmax" attr { key: "T" value { type: DT_FLOAT } } inputs { dtype: DT_FLOAT shape { unknown_rank: true } } device { type: "CPU" vendor: "AuthenticAMD" model: "248" frequency: 1797 num_cores: 16 environment { key: "cpu_instruction_set" value: "SSE, SSE2, SSE3" } environment { key: "eigen" value: "3.4.90" } l1_cache_size: 32768 l2_cache_size: 524288 l3_cache_size: 8388608 memory_size: 268435456 } outputs { dtype: DT_FLOAT shape { unknown_rank: true } }


21/21 [==============================] - ETA: 0s - loss: 10114.5000

2023-11-06 18:12:38.614082: W tensorflow/core/grappler/costs/op_level_cost_estimator.cc:690] Error in PredictCost() for the op: op: "Softmax" attr { key: "T" value { type: DT_FLOAT } } inputs { dtype: DT_FLOAT shape { unknown_rank: true } } device { type: "CPU" vendor: "AuthenticAMD" model: "248" frequency: 1797 num_cores: 16 environment { key: "cpu_instruction_set" value: "SSE, SSE2, SSE3" } environment { key: "eigen" value: "3.4.90" } l1_cache_size: 32768 l2_cache_size: 524288 l3_cache_size: 8388608 memory_size: 268435456 } outputs { dtype: DT_FLOAT shape { unknown_rank: true } }


21/21 [==============================] - 4s 132ms/step - loss: 10114.5000 - val_loss: 7771.9370
Epoch 2/50
21/21 [==============================] - 2s 111ms/step - loss: 4684.9409 - val_loss: 3268.7039
Epoch 3/50
21/21 [==============================] - 2s 103ms/step - loss: 2834.5518 - val_loss: 2333.6768
Epoch 4/50
21/21 [==============================] - 2s 111ms/step - loss: 2149.0515 - val_loss: 1844.4042
Epoch 5/50
21/21 [==============================] - 2s 112ms/step - loss: 1784.2109 - val_loss: 1544.6641
Epoch 6/50
21/21 [==============================] - 3s 135ms/step - loss: 1564.7229 - val_loss: 1375.9373
Epoch 7/50
21/21 [==============================] - 2s 110ms/step - loss: 1451.1593 - val_loss: 1588.0636
Epoch 8/50
21/21 [==============================] - 3s 125ms/step - loss: 1415.1405 - val_loss: 1270.5376
Epoch 9/50
21/21 [==============================] - 2s 112ms/step - loss: 1357.9264 - val_loss: 1221.3325
Epoch 10/50
21/21 [==============================] - 2s 

In [74]:
# Получите прогнозы модели на тестовых данных (предположим, что модель называется model)
y_pred = model.predict(X_test)

# Преобразуйте прогнозы в одномерный массив
# y_pred = y_pred.ravel()
y_pred = y_pred[:,-1,-1]
# MAE (Mean Absolute Error)
mae = mean_absolute_error(y_test, y_pred)
print(f"Mean Absolute Error (MAE): {mae}")

# MAPE (Mean Absolute Percentage Error)
def calculate_mape(y_true, y_pred):
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

mape = calculate_mape(y_test, y_pred)
print(f"Mean Absolute Percentage Error (MAPE): {mape:.2f}%")

# Создайте DataFrame для сравнения и визуализации результатов
temp_df = pd.DataFrame({'y_test': y_test, 'y_pred': y_pred}, index=y_test.index)

 3/21 [===>..........................] - ETA: 0s

2023-11-06 18:14:09.021066: W tensorflow/core/grappler/costs/op_level_cost_estimator.cc:690] Error in PredictCost() for the op: op: "Softmax" attr { key: "T" value { type: DT_FLOAT } } inputs { dtype: DT_FLOAT shape { unknown_rank: true } } device { type: "CPU" vendor: "AuthenticAMD" model: "248" frequency: 1797 num_cores: 16 environment { key: "cpu_instruction_set" value: "SSE, SSE2, SSE3" } environment { key: "eigen" value: "3.4.90" } l1_cache_size: 32768 l2_cache_size: 524288 l3_cache_size: 8388608 memory_size: 268435456 } outputs { dtype: DT_FLOAT shape { unknown_rank: true } }


21/21 [==============================] - 1s 42ms/step
Mean Absolute Error (MAE): 17.228620476437055
Mean Absolute Percentage Error (MAPE): inf%


In [75]:
temp_df.iplot()