In [74]:
import numpy as np

class LaplaceDistribution:    
    @staticmethod
    def mean_abs_deviation_from_median(x: np.ndarray):
        '''
        Args:
        - x: A numpy array of shape (n_objects, n_features) containing the data
          consisting of num_train samples each of dimension D.
        '''
        ####
        # Do not change the class outside of this block
        # Your code here
        n_objects = x.shape[0]
        n_features = x.shape[1]
        mad = np.zeros(n_objects)
        for i in range(n_objects):
            mad[i] = np.sum(np.abs(x[i,:] - np.median(np.sort(x[i])))) / n_features
        ####

    def __init__(self, features):
        '''
        Args:
            feature: A numpy array of shape (n_objects, n_features). Every column represents all available values for the selected feature.
        '''
        ####
        # Do not change the class outside of this block
        self.loc = np.median(features, axis=0)
        self.scale = (np.sum(np.abs(features - loc), axis=0) / len(features))
        ####


    def logpdf(self, values):
        '''
        Returns logarithm of probability density at every input value.
        Args:
            values: A numpy array of shape (n_objects, n_features). Every column represents all available values for the selected feature.
        '''
        ####
        # Do not change the class outside of this block
        return np.log(1/(2 * self.scale)) +np.log( np.exp(-(np.abs(values - self.loc) / self.scale)))
        ####
        
    
    def pdf(self, values):
        '''
        Returns probability density at every input value.
        Args:
            values: A numpy array of shape (n_objects, n_features). Every column represents all available values for the selected feature.
        '''
        return np.exp(self.logpdf(values))

In [75]:
lap = LaplaceDistribution(d)
lap.pdf(d)

/tmp/ipykernel_164441/342855466.py:41: RuntimeWarning: divide by zero encountered in divide
  return np.log(1/(2 * self.scale)) +np.log( np.exp(-(np.abs(values - self.loc) / self.scale)))
/tmp/ipykernel_164441/342855466.py:41: RuntimeWarning: invalid value encountered in divide
  return np.log(1/(2 * self.scale)) +np.log( np.exp(-(np.abs(values - self.loc) / self.scale)))


array([[       nan, 0.01066866,        nan, 0.01867015,        nan,
               nan,        nan, 0.01867015, 0.125     , 0.01066866],
       [       nan, 0.21428571,        nan, 0.375     ,        nan,
               nan,        nan, 0.375     , 0.125     , 0.21428571],
       [       nan, 0.21428571,        nan, 0.375     ,        nan,
               nan,        nan, 0.375     , 0.00622338, 0.21428571]])

In [2]:
import numpy as np
from statsmodels import robust

#define data
data = np.array([1, 2, 2, 3, 5, 7, 7, 7, 7, 9])

#calculate MAD
robust. mad (data)

2.965204437011204

In [16]:
m = np.median(data)
avr = np.mean(data)

avr , m

(5.0, 6.0)

In [18]:
mad = np.sum(np.abs(data - avr)) / len(data)
mad

2.4

In [3]:
d = np.asarray([[1, 9, 2, 7, 5, 7, 7, 3, 7, 2], [1, 2, 2, 3, 5, 7, 7, 7, 7, 9],[1, 2, 2, 3, 5, 7, 7, 7, 19, 9]])
x = d
x.shape

(3, 10)

In [4]:
n_objects = x.shape[0]
n_features = x.shape[1]
mad = np.zeros(n_objects)
for i in range(x.shape[0]):
    mad[i] = np.sum(np.abs(x[i,:] - np.median(np.sort(x[i])))) / n_features

mad

array([2.4, 2.4, 3.6])

In [42]:
print(range(d.shape[0]))

range(0, 3)


In [5]:

mad = np.zeros(d.shape[0])
for i in range(d.shape[0]):
            mad[i] = np.sum(np.abs(d[i,:]- np.median(np.sort(d[i])))) / d.shape[1]
mad

array([2.4, 2.4, 3.6])

In [6]:
np.sum(np.abs(d[i,:] - np.median(np.sort(d[i,:])))) / len(d[i])


loc = np.median(np.sort(d[:, np.arange(0,d.shape[1])]), axis=1)
loc

array([6., 6., 6.])

In [27]:
d.shape

(3, 10)

In [28]:
m = np.median(d)
avr = np.mean(d)

avr , m

(5.181818181818182, 7.0)

In [18]:
d = np.sort(np.asarray([1, 9, 2, 7, 5, 7, 7, 3, 7, 2, 8]))
print(d)

[1 2 2 3 5 7 7 7 7 8 9]


In [10]:
d = np.asarray([1, 2, 2, 3, 5, 7, 7, 7, 7, 8, 9])

In [19]:
mad = np.sum(np.abs(d - np.mean(d))) / len(d)
mad

2.4297520661157024

In [24]:
robust. mad (d)

2.965204437011204

In [25]:
loc.reshape(3,1)

array([[6.],
       [6.],
       [6.]])

In [28]:
np.asarray([[1], [1], [1]])

array([[1],
       [1],
       [1]])

In [ ]:
loc

In [35]:
d - loc.reshape(3,1)
mad

array([2.4, 2.4, 3.6])

In [34]:
scale = 1 / d.shape[1] * np.sum(np.abs(d - loc.reshape(3,1)), axis=1)
scale

array([2.4, 2.4, 3.6])

In [47]:
np.log(1/2 * scale.reshape(3,1)) * np.exp(-(np.abs(d - loc.reshape(3,1)) / scale.reshape(3,1)))

array([[0.02270167, 0.052236  , 0.03443609, 0.12019378, 0.12019378,
        0.12019378, 0.12019378, 0.052236  , 0.12019378, 0.03443609],
       [0.02270167, 0.03443609, 0.03443609, 0.052236  , 0.12019378,
        0.12019378, 0.12019378, 0.12019378, 0.12019378, 0.052236  ],
       [0.1465659 , 0.19349525, 0.19349525, 0.25545103, 0.4452279 ,
        0.4452279 , 0.4452279 , 0.4452279 , 0.01588306, 0.25545103]])

In [61]:
(np.exp(-(np.abs(d - loc.reshape(3,1))))/ scale.reshape(3,1))*scale.reshape(3,1)

array([[6.73794700e-03, 4.97870684e-02, 1.83156389e-02, 3.67879441e-01,
        3.67879441e-01, 3.67879441e-01, 3.67879441e-01, 4.97870684e-02,
        3.67879441e-01, 1.83156389e-02],
       [6.73794700e-03, 1.83156389e-02, 1.83156389e-02, 4.97870684e-02,
        3.67879441e-01, 3.67879441e-01, 3.67879441e-01, 3.67879441e-01,
        3.67879441e-01, 4.97870684e-02],
       [6.73794700e-03, 1.83156389e-02, 1.83156389e-02, 4.97870684e-02,
        3.67879441e-01, 3.67879441e-01, 3.67879441e-01, 3.67879441e-01,
        2.26032941e-06, 4.97870684e-02]])

In [21]:
m = np.median(d, axis=1).reshape(d.shape[0],1)
m

array([[6.],
       [6.],
       [6.]])

In [22]:
d- m

array([[-5.,  3., -4.,  1., -1.,  1.,  1., -3.,  1., -4.],
       [-5., -4., -4., -3., -1.,  1.,  1.,  1.,  1.,  3.],
       [-5., -4., -4., -3., -1.,  1.,  1.,  1., 13.,  3.]])

In [29]:

loc = np.median(d, axis=1).reshape(d.shape[0],1)

scale = np.sum(np.abs(d - loc), axis=1) / d.shape[1]
scale

array([2.4, 2.4, 3.6])

In [64]:
loc = np.median(d, axis=0).reshape(1,d.shape[1])
scale = (np.sum(np.abs(d - loc) / len(d), axis=0)).reshape(1,d.shape[1])
scale


array([[0.        , 2.33333333, 0.        , 1.33333333, 0.        ,
        0.        , 0.        , 1.33333333, 4.        , 2.33333333]])

In [61]:
(np.sum(np.abs(d - loc)) / len(d))

11.333333333333334

In [71]:
loc = np.median(d, axis=0)#.reshape(1,d.shape[1])
loc

array([1., 2., 2., 3., 5., 7., 7., 7., 7., 9.])